In [361]:
import pandas as pd
import numpy as np
import scipy.optimize

In [74]:
sigma_ = np.array([0.2,0.3,0.4])
pho_ = np.array([-0.8,0.5,-0.2])
lambda_ = np.array([0.5,0.7,0.8])

In [75]:
pho = np.array([[1,0.8,0.2],[0.8,1,0.5],[0.2,0.5,1]])

In [76]:
sigma = np.outer(np.array([sigma_]).reshape(-1,1),sigma_)

In [77]:
cov = sigma*pho

In [122]:
A = np.linalg.cholesky(cov).T

In [123]:
b = np.dot(A,lambda_)

In [124]:
scipy.optimize.nnls(A,b)

(array([0.5, 0.7, 0.8]), 0.0)

In [391]:
sigma_ = np.array([0.1,0.2,0.3,0.4])

lambda_ = np.array([0.6,0.3,0.5,0.2])
pho = np.array([[1,-0.2,-0.3,-0.4],[-0.2,1,0.5,0.6],[-0.3,0.5,1,0.9],[-0.4,0.6,0.9,1]])
sigma = np.outer(np.array([sigma_]).reshape(-1,1),sigma_)
cov = sigma*pho

In [392]:
pho

array([[ 1. , -0.2, -0.3, -0.4],
       [-0.2,  1. ,  0.5,  0.6],
       [-0.3,  0.5,  1. ,  0.9],
       [-0.4,  0.6,  0.9,  1. ]])

In [423]:
fun = lambda x: np.dot(np.dot(x,cov),x)
x = np.array([0.5,0.5,0.5,0.5])
bnds = [(0.1,None), (0,None),(0,None),(0,None)]

In [424]:
res = scipy.optimize.minimize(fun,x0=x,bounds=bnds)

In [425]:
res

      fun: 8.400002306356416e-05
 hess_inv: <4x4 LbfgsInvHessProduct with dtype=float64>
      jac: array([1.67961590e-03, 1.61152989e-04, 3.62594225e-04, 3.84356311e-06])
  message: 'CONVERGENCE: NORM_OF_PROJECTED_GRADIENT_<=_PGTOL'
     nfev: 50
      nit: 9
     njev: 10
   status: 0
  success: True
        x: array([0.1       , 0.        , 0.        , 0.01001201])

In [385]:
res.x

array([0.89000016, 0.3       , 0.5       , 0.2       ])

In [386]:
np.linalg.eig(cov)

(array([0.25489157, 0.0071416 , 0.01189306, 0.02607377]),
 array([[ 0.07597826, -0.83322623, -0.54749673, -0.01444566],
        [-0.2548014 ,  0.12949122, -0.20774738, -0.93549415],
        [-0.5630241 ,  0.37039864, -0.65105029,  0.34920228],
        [-0.78250074, -0.38957788,  0.48293051,  0.05195952]]))

In [387]:
np.linalg.inv(cov)

array([[122.44897959,  -5.10204082, -13.60544218,  22.95918367],
       [ -5.10204082,  39.79591837,   6.12244898, -16.58163265],
       [-13.60544218,   6.12244898,  60.77097506, -44.21768707],
       [ 22.95918367, -16.58163265, -44.21768707,  43.36734694]])

In [388]:
cov

array([[ 0.01 , -0.004, -0.009, -0.016],
       [-0.004,  0.04 ,  0.03 ,  0.048],
       [-0.009,  0.03 ,  0.09 ,  0.108],
       [-0.016,  0.048,  0.108,  0.16 ]])

In [262]:
np.dot(np.dot(res.x,cov),res.x)

0.06500000000000003

In [258]:
np.dot(cov,x-res.x)

array([ 0.035, -0.05 ,  0.035])

In [285]:
np.linalg.cholesky(cov)

array([[ 0.5       ,  0.        ,  0.        ],
       [-0.1       ,  0.48989795,  0.        ],
       [ 0.25      ,  0.40824829,  0.14433757]])

In [286]:
cov

array([[ 0.25 , -0.05 ,  0.125],
       [-0.05 ,  0.25 ,  0.175],
       [ 0.125,  0.175,  0.25 ]])

In [275]:
res.x

array([0.5, 0.7, 0.5])

In [274]:
x

array([0.5, 0.5, 0.5])

In [318]:
cov

array([[ 0.01 , -0.018,  0.006],
       [-0.018,  0.04 ,  0.042],
       [ 0.006,  0.042,  0.09 ]])

In [319]:
np.linalg.eig(cov)

(array([-0.00586793,  0.03185575,  0.11401219]),
 array([[-0.76307388, -0.64527402, -0.03660175],
        [-0.57308054,  0.64934338,  0.49993188],
        [ 0.29882595, -0.40246071,  0.86529095]]))

In [344]:
pho = np.array([[1,-0.9,-0.1],[-0.9,1,-0.9],[-0.9,-0.1,1]])

In [347]:
pho

array([[ 1. , -0.9, -0.1],
       [-0.9,  1. , -0.9],
       [-0.9, -0.1,  1. ]])

In [348]:
np.linalg.eig(pho)

(array([-0.25601464+0.j        ,  1.62800732+0.43952199j,
         1.62800732-0.43952199j]),
 array([[ 0.54436608+0.j        , -0.45837402-0.36900683j,
         -0.45837402+0.36900683j],
        [ 0.71007963+0.j        ,  0.06785141+0.48133828j,
          0.06785141-0.48133828j],
        [ 0.44660104+0.j        ,  0.64609355+0.j        ,
          0.64609355-0.j        ]]))

In [389]:
cov+cov.T

array([[ 0.02 , -0.008, -0.018, -0.032],
       [-0.008,  0.08 ,  0.06 ,  0.096],
       [-0.018,  0.06 ,  0.18 ,  0.216],
       [-0.032,  0.096,  0.216,  0.32 ]])

In [390]:
np.linalg.eig(cov+cov.T)

(array([0.50978313, 0.0142832 , 0.02378613, 0.05214754]),
 array([[ 0.07597826, -0.83322623, -0.54749673, -0.01444566],
        [-0.2548014 ,  0.12949122, -0.20774738, -0.93549415],
        [-0.5630241 ,  0.37039864, -0.65105029,  0.34920228],
        [-0.78250074, -0.38957788,  0.48293051,  0.05195952]]))